// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SourceNotes.Data
{
    public partial class Comment
    {
        public int CommentId { get; set; }
        public DateTime CommentDateTime { get; set; }
        public string CommentText { get; set; }
        public int CommentNotesId { get; set; }
        public string CommentFromUser { get; set; }
        public byte[] SsmaTimeStamp { get; set; }

        public virtual AspNetUsers CommentFromUserNavigation { get; set; }
        public virtual Note CommentNotes { get; set; }
    }
}