// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SourceNotes.Data
{
    public partial class Keyword
    {
        public Keyword()
        {
            NotesToKeyword = new HashSet<NotesToKeyword>();
        }

        public int KeywordId { get; set; }
        public string KeywordName { get; set; }

        public virtual ICollection<NotesToKeyword> NotesToKeyword { get; set; }
    }
}