// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SourceNotes.Data
{
    public partial class LbEntry
    {
        public int LbEntryId { get; set; }
        public string LbEntryUser { get; set; }
        public DateTime LbEntryDateTime { get; set; }
        public string LbEntryText { get; set; }
        public int LabBookProjectId { get; set; }
        public byte[] SsmaTimeStamp { get; set; }

        public virtual Project LabBookProject { get; set; }
        public virtual AspNetUsers LbEntryUserNavigation { get; set; }
    }
}