// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SourceNotes.Data
{
    public partial class Note
    {
        public Note()
        {
            Comment = new HashSet<Comment>();
            NotesToKeyword = new HashSet<NotesToKeyword>();
            NotesToPerson = new HashSet<NotesToPerson>();
        }

        public int NoteId { get; set; }
        public string NoteText { get; set; }
        public DateTime NoteDocDate { get; set; }
        public int NoteProjectId { get; set; }
        public int NoteSourceId { get; set; }
        public string NoteUserAuthor { get; set; }
        public byte[] SsmaTimeStamp { get; set; }

        public virtual Project NoteProject { get; set; }
        public virtual Sources NoteSource { get; set; }
        public virtual AspNetUsers NoteUserAuthorNavigation { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<NotesToKeyword> NotesToKeyword { get; set; }
        public virtual ICollection<NotesToPerson> NotesToPerson { get; set; }
    }
}