// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SourceNotes.Data
{
    public partial class Sources
    {
        public Sources()
        {
            Note = new HashSet<Note>();
        }

        public int SourceSourceId { get; set; }
        public string SourceTextDetails { get; set; }
        public byte[] NoteTimeStamp { get; set; }

        public virtual ICollection<Note> Note { get; set; }
    }
}